language: c
sudo: required
services: docker
addons:
  homebrew:
    packages: swig

script: "./packaging/travis/travis.sh"
after_failure: "cat cctools.test.fail"

notifications:
  email:
    on_success: always
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos6
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos7
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-debian9.9
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-fedora30
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-ubuntu16.04
deploy:
  provider: releases
  file: /tmp/cctools-*.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    repo: cooperative-computing-lab/cctools
    tags: true
  api-key:
    secure: N2shk/iZkkpHC8pRZLKaVr/hJKfc0QzGwTwkvGLdLE0HvlMP/hI8AXuxB/qAIjFU1cw+Mx4Ke96VysrBzfPDUEsw8LT+yNYtLSmFlMbwD8WKpRRrwEdx49KdmOTw9mt1utv7+yEWB5iRMztS9I7Vr5eTgtWmLG/iHGJGjJPGVc8=
