site_name: CCTools Documentation
site_url: https://cctools.readthedocs.io/en/latest
site_author: Cooperative Computing Lab at the University of Notre Dame
copyright: Copyright (C) 2022 The University of Notre Dame

nav:
    - Getting Started:
        - About: 'about.md'
        - Installation: 'install/index.md'
        - Getting Help: 'help.md'
    - Software:
        - TaskVine: 'taskvine/index.md'
        - Work Queue: 'work_queue/index.md' 
        - Makeflow: 'makeflow/index.md'
        - JX Workflow Language: 'jx-workflow/index.md'
        - Resource Monitor: 'resource_monitor/index.md'
        - Parrot: 'parrot/index.md'
        - Chirp: 'chirp/index.md'
        - Catalog Server: 'catalog/index.md'
        - Poncho: 'poncho/index.md'
    - Research Prototypes:
        - AWE: 'awe/index.md'
        - Confuga: 'confuga/index.md'
        - Umbrella: 'umbrella/index.md'
        - Prune: 'prune/index.md'
    - Reference:
        - Man Pages: 'man_pages.md'
        - Network Configuration: 'network/index.md'
        - JX Expression Language: 'jx/index.md'
        - Chirp Reference: 'chirp/chirp_protocol.md'
        - API Reference: 'api/html/index.html'

extra_css:
    - css/tabs.css

markdown_extensions:
    - toc:
    - admonition:
    - pymdownx.tabbed:
    - pymdownx.superfences:
    - pymdownx.snippets:
        base_path: doc/manuals

permalink: True

docs_dir: doc/manuals
site_dir: doc/mkdocs-site

theme: readthedocs
